sonar.projectKey=ecommerce-microservices
sonar.organization=anbuselvam-s
sonar.projectName=E-Commerce Microservices
sonar.projectVersion=1.0

sonar.sources=ecommerce-frontend/src,ecommerce-backend/auth-service/src,ecommerce-backend/cart-service/src,ecommerce-backend/inventory-service/src,ecommerce-backend/notification-service/src,ecommerce-backend/notification-worker/src,ecommerce-backend/order-service/src,ecommerce-backend/payment-service/src,ecommerce-backend/product-service/src

sonar.tests=ecommerce-frontend/src/test,ecommerce-backend/testing

sonar.javascript.lcov.reportPaths=ecommerce-frontend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/.git/**,**/*.zip,**/.serverless/**,**/serverless/**,**/*.config.js,**/*.config.cjs,**/*.config.mjs,**/vite.config.js,**/jest.config.js,**/tests/**,**/__tests__/**,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx,**/mocks/**,**/__mocks__/**
